services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

# docker-compose -f docker-file.postgres.yml up -
